### ISSUE TITLE
validation not working with handlebars

### ISSUE THREAD

**Issue by rbarman** [alinex/node-validator#2]
Validation does not seem to work for handlebars. The value of  '{{#if}}' is not valid handlebars syntax, yet when I run the code below, it does not register an error.
I tried the code below via https://tonicdev.com/npm/alinex-validator
```
validator = require("alines-validator")

validator.check({
    name:'test',
    value: '{{#if}}',
    schema: {
        type: 'handlebars'
    }
}, function(err, result){
    if(err) {
        console.log(err);
    }
    else {
        console.log(result);
    }
})
```

**Comment by alinex** [comment]
You forgot to close the if tag. And without a content it is useless.

**Comment by alinex** [comment]
I checked it again and I get the following error in your example:

     Error: Parse error on line 1:
    {{#if}}
    -------^
    Expecting 'COMMENT', 'CONTENT', 'OPEN_RAW_BLOCK', 'OPEN_BLOCK', 'OPEN_INVERSE', 'OPEN_INVERSE_CHAIN', 'INVERSE', 'OPEN_ENDBLOCK', 'OPEN', 'OPEN_UNESCAPED', 'OPEN_PARTIAL', 'OPEN_PARTIAL_BLOCK', got 'EOF'

Look at http://alinex.github.io/develop/lang/handlebars.html#built-in-helpers for how to use the handlebars block helper.

And if you use `value: '{{#if name}}{{name}}{{/if}}'` you should get the desired output of a function which then can be called with the variable `name` in the context.
